
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreSQL.defer
DEFER_NAME					= ThorsNisseCore
LDLIBS_EXTERN_BUILD			+= crypto event boost ThorsDB ThorSerialize

include $(THORSANVIL_ROOT)/build/tools/Makefile

