
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsImp.slib
LDLIBS						= -levent -lboost_system -lboost_coroutine
LINK_LIBS					= ThorsNisse ThorsNisseSocket
UNITTEST_LINK_LIBS			= ThorsNisse ThorsNisseSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile




