git:
    submodules: false
language: cpp
before_install:
    - ./.build/travis/presetup ${TRAVIS_OS_NAME}
install:
    - ./.build/travis/setup ${TRAVIS_OS_NAME}
    - sudo apt-get install -qq libevent-dev
script:
    - ./configure --with-boost=/tmp/extra --disable-ThorsSQL --disable-ThorsSerialize --with-thor-build-on-travis
    - LD_LIBRARY_PATH=/tmp/extra/lib:usr/local/lib make
after_success:
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - "/^Feature-.*$/"
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
