
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseProtocolSimple.a
LDLIBS_EXTERN_BUILD			+= event boost
LINK_LIBS					+= ThorsNisseCoreService ThorsNisseCoreSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile

