
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsTroll.slib
LDLIBS						= -levent -lboost_system -lboost_coroutine
LINK_LIBS					= ThorsNisse ThorsNisseSocket
VERA_IGNORE					= http_parser.cpp http_parser.h

include $(THORSANVIL_ROOT)/build/tools/Makefile




