
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreService.a
LDLIBS_EXTERN_BUILD			+= event boost
LINK_LIBS					+= ThorsNisseCoreSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile

