
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreService.defer
DEFER_NAME					= ThorsNisseCore
LDLIBS_EXTERN_BUILD			+= event boost
UNITTEST_LINK_LIBS			+= UnitTestThorsNisseCoreSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile

