
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreService.defer
DEFER_NAME					= ThorsNisseCore
LDLIBS_EXTERN_BUILD			+= event boost ThorsDB
LINK_LIBS					+= ThorsSocket

include $(THORSANVIL_ROOT)/build/tools/Makefile

