
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreSocket.defer
DEFER_NAME					= ThorsNisseCore
LDLIBS_EXTERN_BUILD			+= event ThorSerialize

include $(THORSANVIL_ROOT)/build/tools/Makefile

