
THORSANVIL_ROOT				?= $(realpath ../../../)
COVERAGE_REQUIRED			= 0

TARGET						= ThorsNisseExpressSimple.defer
DEFER_NAME					= ThorsNisseExpress
LDLIBS_EXTERN_BUILD			+= event boost dl ThorsDB
LINK_LIBS					+= ThorsNisseCore

include $(THORSANVIL_ROOT)/build/tools/Makefile

