
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseExpressAddSite.defer
DEFER_NAME					= ThorsNisseExpress
LDLIBS_EXTERN_BUILD			+= event boost ThorSerialize ThorsDB
LDLIBS						+= -ldl

include $(THORSANVIL_ROOT)/build/tools/Makefile

