
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsSocket.slib
LDLIBS						= -levent

%/Socket.o:			FILE_WARNING_FLAGS	+= -Wno-unknown-pragmas

include $(THORSANVIL_ROOT)/build/tools/Makefile

