
# This line was added so the documentation tool can pick up the namespace
#using namespace ThorsAnvil::Nisse::Core::Utility

THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= ThorsNisseCoreUtility.head

include $(THORSANVIL_ROOT)/build/tools/Makefile

