
THORSANVIL_ROOT				= $(realpath ../)

BUILD_EXAMPLE_yes			= Example
TARGET						= Core Protocol Express NodeCXX $(BUILD_EXAMPLE_$(HAVE_ThorsSQL))

include $(THORSANVIL_ROOT)/build/tools/Project.Makefile




