
THORSANVIL_ROOT				?= $(realpath ../../../)

TARGET						= AddBeer.slib
LDLIBS_EXTERN_BUILD			+= event boost ThorSerialize ThorsDB
LINK_LIBS					+= ThorsNisseExpress

include $(THORSANVIL_ROOT)/build/tools/Makefile

